FROM node:18.7.0

WORKDIR /mytrello

#RUN npm install -g typescript@3.5.3
#RUN npm install -g jquery@3.6.0
#RUN npm install -g bootstrap@5.2.0
#RUN npm install -g express@4.18.1 --save
#RUN npm install -g nodemon@2.0.11 --save-dev
#RUN npm install

#ADD server.js /mytrello/server.js

USER node
ENV PORT 3000
EXPOSE 3000

ENTRYPOINT "/bin/bash"
